name: Deploy Heroku Review App
description: Create a Heroku review app when a PR is raised by someone with write or admin access
runs:
  using: docker
  image: Dockerfile
branding:
  icon: book-open
  color: orange
outputs:
  review-app-name:
    description: "The name of the deployed review app"
