name: "Start Workflow (new)"
author: "Oliver Pike"
description: "Parses commit messages to extract data like the pull request id"
inputs:
  pull-request-id:
    description: "pull request #"
    required: true
  token:
    description: "Github Token"
    required: true
outputs:
  branch-name:
    description: "pull request branch name"
  pull-request-id:
    description: "pull request id extracted from the commit message"
  heroku-app-name:
    description: "name of the heroku app"
  instance-name:
    description: "name of the database and the google bucket"
  deploy-status:
    description: "status of the deployment"
runs:
  using: "node12"
  main: "index.js"
