name: "Check label"
author: "Oliver Pike"
description: "Retrieves the heroku review app host from a label"
inputs:
  token:
    description: "Github Token"
    required: true
  pr_number1:
    description: "pull request number source 1"
    required: true
  pr_number2:
    description: "pull request number source 2"
    required: true
outputs:
  label:
    description: "heroku review app host from a PR label"
runs:
  using: "node12"
  main: "./dist/index.js"
